# -*- coding: utf-8 -*-
"""Assignment 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gKlicgsox3kHyhJ2ghGwMYdMdQ4cpAFw
"""

l = list(map(int, input("Enter numbers for the List: ").split()))
s = sum(l)
multiplier = int(input("Enter the num to multiply the whole list by: "))
mlist = [i*2 for i in l]
copy_l = l.copy()
copy_l.reverse()
odds = [i for i in l if i%2 != 0]
print("the list itself",(l))
print("Sum:", s)
print(f"Min number : {min(l)}")
print(f"reversed list: {copy_l}")
print("only odd nums", (odds))
print(f"numbers after multiplication", (mlist))

l = list(map(int, input("Enter numbers for the List: ").split()))
x = int(input("The number u wanna use to filter list(all smaller one will be sorted out): "))
filt_x_l = [i for i in l if i>x]
nonnegative_l = [i for i in l if i>=0]
nonnegative_l_avg = sum(nonnegative_l)/len(nonnegative_l)
print("the list itself",(l))
print(f"only the numbers which are bigger tnen {x}: {filt_x_l}")
print(f"the avg of nonnegative: {nonnegative_l_avg}")

l = list(map(int, input("Enter numbers for the List: ").split()))
x = int(input("Filter nums thet less then this"))
y = int(input("Num to check if divisible and find the sum of those who is: "))
l_x = [i for i in l if i<x]
l_y = [i for i in l if i%y==0]
l_squares = [i*i for i in l]
l_nonnegative = [i for i in l if i>=0]
print("nonnegative", l_nonnegative)
print("squered:",l_squares)
print(f"sum of nums divisible by {y} {sum(l_y)}")
print("the amount of nums less then x: ", len(l_x))

l = list(input().split())
pref = input("enter ur prefix to filt: ")
x = len(pref)
l_filt = [i for i in l if i[:x]==pref]
l_palindrome = [i for i in l if i[::-1]==i[::1]]
print("palindromes:", l_palindrome)
print(f"words that start with prefix {pref}: {l_filt}")

l = list(map(int,input("Nums for list: ").split()))
N = int(input("sum of how many nums:" ))
l_N = [num for i,num in enumerate(l) if i<=N ]
Sum_n = sum(l_N)
print(Sum_n)

l = list(map(int,input("Nums for list: ").split()))
logic = []
x = int(input("U are dividing by: "))
for i in l:
  if i%x!=0:
    logic.append(False)
  else:
    logic.append(True)
print(logic)

l = list(map(int,input("Nums for list: ").split()))
x =int(input())
y = int(input())
l_filt = [i for i in l if i % x==0 and i % y!= 0]
print(f"Devisible by {x}, not by {y}: {l_filt}")

l = [1, [2, 3], 4, [5, [6, 7]], 8] # created with help of this video "https://www.youtube.com/watch?v=FK29FtRCB74&ab_channel=ProgrammingandMathTutorials"
def flattened(name_list):
  filtered_list = []
  for i in name_list:
    if isinstance(i,list):
      filtered_list.extend(flattened(i))
    else:
      filtered_list.append(i)
  return  filtered_list
x = flattened(l)
print(x)

#Task3
def task3():
  l = "jkvdfckmwkKJHLS efj  oekwdok LKJKLdm"
  l_2 = [i for i in l if i.isupper()]
  for i in l_2:
    print(i)
#Task4
l = list(map(int, input().split()))
l.sort(reverse=True)
l_2 = l.copy()

print(l)

#Task10
l = list(map(int,input().split()))
multiplied = []
x,y = map(int,input().split())
for i in l:
  if i>x:
    i = i*y
  multiplied.append(i)
print(multiplied)

#Task4(sort )
l = list(map(int,input().split()))
c = []
for i in l:
  a=l.count(i)
  t = (i, a)
  c.append(t)
c.sort(key=lambda с :с[1], reverse=True)
f_l = [i for (i,y) in c ]
print(f_l)

#Task5
l = list(map(int,input().split()))
l_2 = list(map(int,input().split()))
if len(l) == len(l_2):
  l_3 = list(zip(l, l_2))
  print(l_3)
else:
  print(l)
  print(l_2)

#Task6
Pavlo = dict( math = "150", Mova = "124", English = "100" )
Ne_Pavlo = dict( math = "131", Mova = "122", English = "182" )
Zahar = dict( math = "15", Mova = "14", English = "10" )
Spanch_Bob = dict( math = "100", Mova = "100", English = "200" )
Patric = dict( math = "300", Mova = "300", English = "300" )
Lev = dict( math = "200", Mova = "200", English = "200" )


def nmt_sum(*args):
  a = dict()
  math = 0
  Mova = 0
  English = 0
  for name in args:
    for key,value in name.items():
      if key == "math":
        math += int(value)
      elif key == "Mova":
        Mova += int(value)
      elif key == "English":
        English += int(value)
  print(f"Math: {math}")
  print(f"Mova: {Mova}")
  print(f"English: {English}")


nmt_sum(Pavlo,Ne_Pavlo,Lev,Patric)

Pavlo = dict( math = "150", Mova = "124", English = "100" )
Ne_Pavlo = dict( math = "131", Mova = "122", English = "182" )
Zahar = dict( math = "15", Mova = "14", English = "10" )
Spanch_Bob = dict( math = "100", Mova = "100", English = "200" )
Patric = dict( math = "300", Mova = "300", English = "300" )
Lev = dict( math = "200", Mova = "200", English = "200" )
student_grades = dict(Pavlo = Pavlo, Ne_Pavlo = Ne_Pavlo, Zahar= Zahar,
                      Spanch_Bob = Spanch_Bob, Patric=Patric, Lev = Lev)
print (student_grades)
Passed = {imia:"pass" for imia in student_grades.keys()}
for name, grades in student_grades.items():
  for subject in grades:
    if subject<100:


Passed["Pavlo"] = "Ne_Sdal"

print(Passed)

Pavlo = dict( math = "150", Mova = "124", English = "100" )
Ne_Pavlo = dict( math = "131", Mova = "122", English = "182" )
Zahar = dict( math = "15", Mova = "14", English = "10" )
Spanch_Bob = dict( math = "100", Mova = "100", English = "200" )
Patric = dict( math = "300", Mova = "300", English = "300" )
Lev = dict( math = "200", Mova = "200", English = "200" )
student_grades = dict(Pavlo = Pavlo, Ne_Pavlo = Ne_Pavlo, Zahar= Zahar,
                      Spanch_Bob = Spanch_Bob, Patric=Patric, Lev = Lev)
print (student_grades)
Passed = {imia:"pass" for imia in student_grades.keys()}
for name, grades in student_grades.items():
  for subject in grades.values():
    if int(subject)<100:
        Passed[name] = "Ne_Sdal"
        break
    elif int(subject)>200:
        Passed[name] = "Cheater"
        break
for name,status in Passed.items():
  print(f"{name} : {status}")

#Task8
l = list(input().split())
x = int(input("Strings that are lonager, then..."))
count = 0
for string in l:
  if len(string)>x:
    count += 1
print(f"number of strings that are longer: {count}")

#Task9
l = list(input().split())
l_2 = list(input().split())
l_3 = list(zip(l, l_2))
print(l)
print(l_2)
print(l_3)

#Task10
l = list(map(int, input().split()))
y = int(input("Multiplier"))
x = int(input("condition"))
l_2 = [i*y for i in l if i>x ]
print(l_2)